config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students do
    resources :addresses, only: %i[new create]
  end
  resources :courses, only: %i[show]
end

app/models/address.rb
class Address < ApplicationRecord
  validates :city, presence: true
  validates :state, presence: true
  validates :street, presence: true
  validates :zip, presence: true
  belongs_to :student, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student_courses.rb
class StudentCourses < ApplicationRecord
  has_many :students
  has_many :courses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_student, only: %i[new create]

  def new
    render locals: { student: @student,
                     address: Address.new }
  end

  def create
    @student.addresses.create(address_params)

    redirect_to student_path(params[:student_id])
  end

  private

  def set_student
    @student = Student.find(params[:student_id])
  end

  def address_params
    params.require(:address).permit(:description, :city, :state, :zip, :street)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    render locals: { course: Course.find(params[:id]) }
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show update edit destroy]
  def index
    render locals: { students: Student.all }
  end

  def show
    render locals: { student: @student}
  end

  def new
    render locals: { student: Student.new }
  end

  def create
    Student.create(student_params)

    redirect_to students_path
  end

  def edit
    render locals: { student: @student }
  end

  def destroy
    @student.delete

    redirect_to students_path
  end

  def update
    @student.update(student_params)

    redirect_to student_path(@student)
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<%= form_for([student, address]) do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h1>Course show</h1>

<% course.students.each do |student| %>
  <%= student.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'New Student', new_student_path %>
    <%= link_to 'Home', students_path %>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= form_for student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>

<% students.each do |student| %>
  <%= link_to student.name, student_path(student)%>
  <%= link_to  'Delete', student_path(student), method: 'DELETE' %>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_for student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1>Student</h1>

<%= student.name %>
<br>
<%= student.addresses.each do |address| %>
  <%= address.street %>
  <%= address.state %>
  <%= address.zip %>
  <%= address.city %>
  <%= address.description %>
<% end %>

<%= student.courses.each do |course| %>
  <%= course.name %>
<% end %>